services:
  - type: web
    name: ats-resume-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.main:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
